openapi: 3.0.0
info:
  version: 0.9.6
  title: Swarm API
  description: 'A list of the currently provided Interfaces to interact with the swarm, implementing file operations'
security:
  - {}
externalDocs:
  description: Read the documentation @ Swarm-guide
  url: 'https://swarm-guide.readthedocs.io/en/latest/'
servers:
  - url: '{apiRoot}/v1'
    variables:
      apiRoot:
        default: 'http://localhost:8080'
        description: Base address of the local swarm node API
paths:
  
  '/bzz-raw':
    post:
      summary: 'Upload data'
      tags: 
        - 'Endpoints on local swarm node'
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Hash'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bzz-raw/{address}':
    get:
      summary: 'Get addressed data'
      tags: 
        - 'Endpoints on local swarm node'
      parameters:
        - in: path
          name: address
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/BzzAddress'
          required: true
          description: Bzz address of content
      responses:
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response
          
  '/bzz-chunk/{addr}':
    get:
      summary: 'Get Chunk'
      tags: 
        - 'Endpoints on local swarm node'
      parameters:
        - in: path
          name: addr
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/BzzAddress'
          required: true
          description: Bzz address of chunk   
      responses:
        '200':
          description: Retrieved chunk content
          content:
            application/octet-stream:
              schema:
                type: string  
                format: binary
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '404':
          $ref: 'SwarmCommon.yaml#/components/responses/404'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bzz-chunk':
    post:
      summary: 'Upload Chunk'
      tags: 
        - 'Endpoints on local swarm node'
      parameters:
        - in: header
          name: swarm-tag-uid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/UUid'
          required: false
          description: UUid of chunk
        - in: header
          name: swarm-pin
          schema:
            type: boolean
          required: false
          description: Represents the pinning state of the chunk
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/Hash'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bzz-tag/name/{name}':
    post:
      summary: 'Create Tag'
      tags: 
        - 'Endpoints on local swarm node'
      parameters:
        - in: path
          name: name
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/TagName'
          required: true
          description: Tagname
      responses:
        '200':
          description: New Tag Info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response

  '/bzz-tag/uuid/{uuid}':
    get:
      summary: 'Get Tag information using UUid'
      tags: 
        - 'Endpoints on local swarm node'
      parameters:
        - in: path
          name: uuid
          schema:
            $ref: 'SwarmCommon.yaml#/components/schemas/UUid'
          required: true
          description: UUid
      responses:
        '200':
          description: Tag info
          content:
            application/json:
              schema:
                $ref: 'SwarmCommon.yaml#/components/schemas/NewTagResponse'
        '400':
          $ref: 'SwarmCommon.yaml#/components/responses/400'
        '500':
          $ref: 'SwarmCommon.yaml#/components/responses/500'
        default:
          description: Default response